apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-service-deployment
  labels:
    app: crud-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-service
  template:
    metadata:
      labels:
        app: crud-service
    spec:
      containers:
      - name: crud-service
        image: krobus00/crud-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
          - name: APP_NAME
            value: "CRUD Service"
          - name: APP_PORT
            value: "3000"
          - name: ENVIRONMENT
            value: "production"
          - name: MONGO_DSN
            value: "mongodb://mongodb:27017"
          - name: MONGO_DATABASE
            value: "simple_crud"
          - name: ACCESS_TOKEN_SECRET
            value: "ACCESS_TOKEN_SECRET"
          - name: ACCESS_TOKEN_DURATION_IN_SECOND
            value: "900"
          - name: REFRESH_TOKEN_SECRET
            value: "REFRESH_TOKEN_SECRET"
          - name: REFRESH_TOKEN_DURATION_IN_SECOND
            value: "604800"
 
---

apiVersion: v1
kind: Service
metadata:
  name: crud-service
  labels:
    service: crud-service
spec:
  type: NodePort
  selector:
    app: crud-service
  ports:
  - port: 3000
    targetPort: 3000